### PR TITLE
Fix empty link content assignment

### LINKED ISSUE #342: Failure when setting content for ScLink after previously assigning an empty one.
```c++
ScLink link(ctx, linkAddr);
link.Set<std::string>("asdf");
link.Set<std::string>("");
link.Set<std::string>("asdf")
```
`sc-machine/sc-memory/sc-core/sc-store/sc_storage.c:957:sc_storage_set_link_content: assertion failed: (__r == SC_RESULT_OK)`

### LINKED ISSUE #343: Incorrectly stored value after assigning empty content to ScLink
```c++
ScLink link(ctx, linkAddr);
link.Set<std::string>("asdf");
link.Set<std::string>("");
EXPECT_EQ(link.GetAsString(), "");
```
`sc-machine/sc-memory/tests/sc-memory/common/sc-link.cpp:72: Failure`
`Expected equality of these values:`
`link.GetAsString() Which is: "asdf"`
 `""`

### PR DESCRIPTION
**Pull request by ValikVityaz**
fixes #342
fixes #343

### CODE REVIEW

File: sc-memory/tests/sc-memory/common/sc-link.cpp [hunk 1]
```diff
@@ -94,4 +94,7 @@ TEST_F(ScLinkTest, as_string)
 
   EXPECT_TRUE(link.Set<uint64_t>(7600000000));
   EXPECT_EQ(link.GetAsString(), "7600000000");
+
+  EXPECT_TRUE(link.Set<std::string>(""));
```
Comment (deniskoronchik) [inline sc-memory/tests/sc-memory/common/sc-link.cpp:98]: Check if we will get value after set

File: sc-memory/tests/sc-memory/common/sc-link.cpp [hunk 2]
```diff
@@ -94,4 +94,7 @@ TEST_F(ScLinkTest, as_string)
...
+  EXPECT_TRUE(link.Set<std::string>("test"));
```
Comment (deniskoronchik) [inline sc-memory/tests/sc-memory/common/sc-link.cpp:99]: same

**Review by deniskoronchik — CHANGES_REQUESTED** [review]
Improve tests

**Review by KovalM — APPROVED** [review]

**Review by MikhailSadovsky — APPROVED** [review]

File: sc-memory/sc-core/sc-store/sc_storage.c [hunk 3]
```diff
@@ -1034,19 +1034,12 @@ sc_result sc_storage_get_link_content(const sc_memory_context *ctx, sc_addr addr
   {
     sc_uint8 len = el->content.data[0];
 
-    if (len != 0)
-    {
-      g_assert(len < SC_CHECKSUM_LEN);
-      gchar *buff = g_new0(gchar, len);
-      memcpy(buff, &el->content.data[1], len);
-      *stream = sc_stream_memory_new(buff, len, SC_STREAM_FLAG_READ, SC_TRUE);
+    g_assert(len < SC_CHECKSUM_LEN);
```
Comment (deniskoronchik) [inline sc-memory/sc-core/sc-store/sc_storage.c:1037]: Old code is stable. This one not.
Also empty sc_link should not generate sc_stream

File: sc-memory/sc-core/sc-store/sc_stream_memory.c [hunk 4]
```diff
@@ -91,7 +91,6 @@ sc_result sc_stream_memory_free_handler(const sc_stream *stream)
 
   if (buffer->data_owner == SC_TRUE)
   {
-    g_assert(buffer->data != 0);
```
Comment (deniskoronchik) [inline sc-memory/sc-core/sc-store/sc_stream_memory.c:94]: Return this assert

File: sc-memory/sc-core/sc-store/sc_stream_memory.c [hunk 5]
```diff
@@ -121,7 +120,8 @@ sc_stream* sc_stream_memory_new(const sc_char *buffer, sc_uint buffer_size, sc_u
   }
 
   g_assert(flags & SC_STREAM_FLAG_READ);
-  g_assert(buffer != null_ptr);
+  if (buffer_size != 0)
```
Comment (deniskoronchik) [inline sc-memory/sc-core/sc-store/sc_stream_memory.c:123]: Make special if to do assert?
Return old one

**Review by deniskoronchik — CHANGES_REQUESTED** [review]
Broken logic

File: sc-memory/sc-core/sc-store/sc_stream_memory.c (hunk 4 above)
Comment (ValikVityaz) [reply sc-memory/sc-core/sc-store/sc_stream_memory.c:94]: What's the value of this assert?

Comment (deniskoronchik) [reply sc-memory/sc-core/sc-store/sc_stream_memory.c:94]: As purpose of any other assert - check the logic. We should not go there, that data is empty.

File: docs/changelog.md [hunk 6]
```diff
@@ -3,6 +3,7 @@
  - **C++**:
     - Migrate test system to `gtest`
     - Remove optional search triples support
+    - Fix issues with assigning empty content to an sc-link (#342, #343)
```
Comment (deniskoronchik) [inline docs/changelog.md:6]:
```suggestion
    - Fix issues with assigning empty content to `ScLink` (#342, #343)
```

File: sc-memory/sc-memory/sc_link.hpp [hunk 7]
```diff
@@ -100,6 +100,11 @@ class ScLink
                          "You use incorrect type. Use IsType<>() to check it");
     }
     ScStreamPtr const stream = m_ctx.GetLinkContent(m_addr);
+
+    // Check for empty content.
+    if (stream && !stream->IsValid())
+      return Type();
```
Comment (deniskoronchik) [inline sc-memory/sc-memory/sc_link.hpp:106]: My proposal is to do such logic:
```cpp
ScStreamPtr ScMemoryContext::GetLinkContent(ScAddr const & addr)
{
  SC_ASSERT(IsValid(), ());

  sc_stream * s = nullptr;
  if (sc_memory_get_link_content(m_context, *addr, &s) != SC_RESULT_OK || s == nullptr)
    return ScStreamPtr();

  return std::make_unique<ScStream>(s);
}
```

Let say, that main function can return `nullptr`. Then we will check that across whole code. The main idea there is to say, that we don't generate `ScStream` for empty contents. Let return pointer will be null.
Because when it is not null developer will have crashes for any function call for returned `ScStream` because internal pointer will be empty. 
Let developer do usage like this:
```cpp
ScStreamPtr const stream = m_ctx.GetLinkContent(m_addr);
if (stream)
{
}
```

instead of 
```cpp
ScStreamPtr const stream = m_ctx.GetLinkContent(m_addr);

if (stream->IsValid())
{
}
```

Understanding, that pointer can be null is native for any developer.

Also this requires change in current function. We should not throw an exception:
```cpp

    if (!stream)
      return Type();

    Type result;
    if (!Stream2Value(stream, result))
    {
        SC_THROW_EXCEPTION(utils::ExceptionCritical,
                           "Error to get value of " + std::to_string(m_addr.Hash()));
    }

    return result;
```

**Review by deniskoronchik — CHANGES_REQUESTED** [review]
Some additional thoughts

File: sc-memory/sc-memory/sc_link.hpp (hunk 7 above)
Comment (ValikVityaz) [reply sc-memory/sc-memory/sc_link.hpp:106]: By doing this we won't be able to differentiate between GetLinkContent() returning a null pointer because of empty content and it returning a null pointer because of some error.

Comment (deniskoronchik) [reply sc-memory/sc-memory/sc_link.hpp:106]: Error throws an exception

Comment (ValikVityaz) [reply sc-memory/sc-memory/sc_link.hpp:106]: I mean an error inside `sc_memory_get_link_content()`, which causes it not to return `SC_RESULT_OK`

Comment (deniskoronchik) [reply sc-memory/sc-memory/sc_link.hpp:106]: Yeah. We can check that and throw an exception

File: sc-memory/sc-memory/sc_memory.cpp [hunk 8]
```diff
@@ -336,9 +336,15 @@ ScStreamPtr ScMemoryContext::GetLinkContent(ScAddr const & addr)
 
   sc_stream * s = nullptr;
   if (sc_memory_get_link_content(m_context, *addr, &s) != SC_RESULT_OK)
+  {
+    SC_THROW_EXCEPTION(utils::ExceptionCritical,
```
Comment (deniskoronchik) [inline sc-memory/sc-memory/sc_memory.cpp:340]: This function should not throws an exception. It should return null ptr. My comment was about throwing exception in `ScLink::Type Get() const` that already exist

**Review by deniskoronchik — CHANGES_REQUESTED** [review]
Remove one exception

**Comment by deniskoronchik** [comment]
Also rebase onto `master`

File: sc-memory/sc-memory/sc_link.hpp [hunk 9]
```diff
@@ -96,15 +96,20 @@ class ScLink
...
+    if (!stream)
+      return Type();
+
     Type result;
-    if (!stream || !Stream2Value(stream, result))
+    if (!Stream2Value(stream, result))
     {
       SC_THROW_EXCEPTION(utils::ExceptionCritical,
-                         "Error to get value of " + std::to_string(m_addr.Hash()));
+                         "Failed to convert the value of " + std::to_string(m_addr.Hash()));
```
Comment (deniskoronchik) [inline sc-memory/sc-memory/sc_link.hpp:112]: Failed to convert? What is a source and target types?
Providing of error should not expose implementation. I think better to return just two types of error:
- Invalid type. We request `type1` but in knowledge base content marked with `type2`
- An common error: we can't get content of sc-link.

Thats all. In other case this error will be changes with changing of internal implementation. This is not very good

**Review by deniskoronchik — CHANGES_REQUESTED** [review]
Small change in exception message

**Review by deniskoronchik — APPROVED** [review]
